In [1]:
# Utils
# ==============================================================================
import warnings
import time

# Plot
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

# Data
# ==============================================================================
import pandas as pd
from sklearn.datasets import (
    make_friedman1,
    make_classification
)

# Model
# ==============================================================================
from sklearn.model_selection import (
    train_test_split,
    ParameterGrid,
    GridSearchCV
)

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

# Metrics
# ==============================================================================
from sklearn.metrics import (
    root_mean_squared_error,
    f1_score
)

# **Info**
---

**@By:** Steven Bernal

**@Nickname:** Kaiziferr

**@Git:** https://github.com/Kaiziferr

# **Config**
---

In [2]:
sns.set(style="darkgrid")
warnings.simplefilter("ignore")
paleta = sns.color_palette("tab10").as_hex()
random_seed = 12354

# **Context**
---

A set of non-linear synthetic data was generated for the regression problem, along with data for the classification problem. Since the goal is to demonstrate a proof of concept, this approach was adopted to minimize processing time.

# **Goals**
---

The objective of this project is to demonstrate the use of the OOB (out-of-bag) score in the random forest.

# **Regression**
---

## **Data**
---

The make_friedman1 function from scikit-learn allows you to generate a non-linear dataset.

In [3]:
X, y = make_friedman1(
    n_samples=1000,
    n_features=8,
    noise=1.8,
    random_state=random_seed
)

In [4]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7
0,0.551963,0.109711,0.029752,0.428018,0.560191,0.794667,0.465564,0.345875
1,0.337109,0.204982,0.450691,0.149433,0.784783,0.296252,0.869173,0.452800
2,0.211150,0.904876,0.333836,0.786745,0.495321,0.447385,0.820702,0.371697
3,0.471441,0.021436,0.237610,0.709758,0.575986,0.411255,0.712220,0.164222
4,0.552286,0.846666,0.785294,0.980033,0.863304,0.053508,0.088855,0.508065


## **Split**
---

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size = 0.8,
    random_state = random_seed
)

## **Model**
---

**Apply Cross Validation**

To validate the performance of the random forest, cross-validation can be used; however, depending on the case, it may be computationally expensive due to the multiple iterations involved. I usually place greater importance on the following parameters:

- n_estimators: Number of trees in the forest.
- criterion: Metric used to measure prediction error.
- min_samples_split: Minimum samples needed to split a node.
- min_samples_leaf: Minimum samples required in each leaf.
- max_features: Number of features considered for each split.
- max_depth: Maximum depth allowed for each tree.

In [6]:
dict_params = ParameterGrid(
    {
        "n_estimators": [100, 150, 200],
        "criterion": ["squared_error", "absolute_error"],
        "min_samples_split": [2, 4, 8],
        "min_samples_leaf": [1, 2, 4, 8],
        "max_features": [0.75, "sqrt", "log2"],
        "max_depth": [None, 20, 30],
    }
)


The test is carried out using five-fold cross-validation in GridSearchCV, with cv=5 to reduce execution time.

In [7]:
start_time = time.time()

GridSearchCV evaluates different combinations of Random Forest hyperparameters using 5-fold cross-validation. It uses RMSE to measure model performance, selects the parameter combination with the best score, and then retrains the model using those optimal parameters.

In [8]:
grid = GridSearchCV(
    estimator = RandomForestRegressor(
        n_jobs=-1,
        random_state=random_seed
    ),
    cv = 5,
    param_grid = dict_params.param_grid[0],
    scoring = "neg_root_mean_squared_error",
    refit =  True,
    verbose = 0,
    return_train_score = True

)
grid.fit(X_train, y_train)

,estimator,RandomForestR...m_state=12354)
,param_grid,"{'criterion': ['squared_error', 'absolute_error'], 'max_depth': [None, 20, ...], 'max_features': [0.75, 'sqrt', ...], 'min_samples_leaf': [1, 2, ...], ...}"
,scoring,'neg_root_mean_squared_error'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,True
,n_estimators,200


In [9]:
end_time = time.time()

For a data science notebook, I would explain it like this:

The GridSearchCV process took approximately **22.1 minutes (1,326.88 seconds)** to complete. This relatively long execution time is mainly due to the combination of **GridSearchCV, 5-fold cross-validation, and Random Forest**.

GridSearchCV does not train the model only once. It evaluates **every possible combination of hyperparameters** defined in the parameter grid. In this case, there are:

- 3 values for `n_estimators`
- 2 values for `criterion`
- 3 values for `min_samples_split`
- 4 values for `min_samples_leaf`
- 3 values for `max_features`
- 3 values for `max_depth`

This results in **648 different hyperparameter combinations**. Since `cv=5`, each combination is trained and evaluated **5 times**, resulting in up to **3,240 model fits**.

The computational cost is even higher because each model is a **Random Forest**, which itself consists of multiple decision trees. For example, when `n_estimators=200`, each individual model requires training 200 trees. Therefore, GridSearchCV can end up training **hundreds of thousands of decision trees** across the entire search.

Although `n_jobs=-1` allows the computation to use all available CPU cores and reduces the runtime, the total number of models and trees that need to be trained is still substantial. Therefore, the **22.1-minute execution time is mainly a consequence of performing an exhaustive hyperparameter search on a computationally intensive ensemble model**.

In [10]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 1021.61430 seconds


** GridSearchCV Results**

- The best-performing configuration achieves a mean validation RMSE of approximately 2.55. The top configurations are very similar, with validation RMSE values ranging from approximately 2.55 to 2.56, indicating that their predictive performance is quite close across the cross-validation folds.

- A consistent pattern can be observed in the selected hyperparameters. All top configurations use squared_error as the splitting criterion, log2 for max_features, and 200 trees in the Random Forest. The best configurations also use a relatively small min_samples_split value, allowing the trees to create more detailed partitions of the training data.

- The results for max_depth=None and max_depth=30 are identical, suggesting that limiting the trees to a depth of 30 does not change the model's validation performance in this case. Similarly, reducing the maximum depth to 20 produces only a negligible difference in RMSE.

- An important observation is the gap between training and validation performance. The best configuration has a training RMSE of approximately 1.09, compared with a validation RMSE of 2.55. This indicates that the model performs substantially better on the data used for training than on the validation folds, which is a signal of overfitting.

- The fourth configuration is particularly interesting: although its validation RMSE is only slightly worse (~2.55), its training RMSE is considerably lower (~0.96). This produces an even larger train–validation gap and suggests that the additional flexibility provided by min_samples_split=2 allows the trees to fit the training data more closely without providing a meaningful improvement in validation performance.

- Overall, the results suggest that several hyperparameter configurations provide very similar validation performance, while their training performance differs considerably. Therefore, selecting a configuration based solely on the lowest validation RMSE may favor a more flexible model without providing a meaningful generalization benefit.

In [11]:
results = pd.DataFrame(grid.cv_results_)
results.filter(regex = '(param.*|mean_t|std_t)') \
    .drop(columns = 'params') \
    .sort_values(['mean_test_score', 'mean_train_score'], ascending = False) \
    .head(4)

,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,mean_test_score,std_test_score,mean_train_score,std_train_score
293,squared_error,30,log2,1,4,200,-2.550536,0.151563,-1.086777,0.013514
77,squared_error,None,log2,1,4,200,-2.550536,0.151563,-1.086777,0.013514
185,squared_error,20,log2,1,4,200,-2.551328,0.151290,-1.086895,0.013175
181,squared_error,20,log2,1,2,150,-2.553251,0.156306,-0.956545,0.009324


In [12]:
best_model_grid = grid.best_estimator_

The selected Random Forest model was evaluated on the independent test set using the Root Mean Squared Error (RMSE). The model achieved a test RMSE of 2.3854.

This result represents the model's expected prediction error on observations that were not used during the hyperparameter selection or model training process. Since the test set was kept separate from the GridSearchCV procedure, this provides a more reliable estimate of the model's performance on unseen data.

Interestingly, the test RMSE (2.3854) is lower than the cross-validation RMSE of approximately 2.55 observed during GridSearchCV. This difference does not necessarily indicate a problem. Cross-validation produces an average validation performance across multiple folds, while the final test RMSE is calculated on one specific holdout sample. Differences between these values can occur due to the particular observations contained in each split.

Therefore, the test result suggests that the selected model maintains good predictive performance on the independent test set. However, the test RMSE should be interpreted together with the training and cross-validation results rather than as evidence that the model is free from overfitting.

In [13]:
y_predict = best_model_grid.predict(X_test)
root_mean_squared_error(y_test, y_predict)

2.3854479050772532

In [14]:
results['relative_gap_%'] = (
    (results['mean_train_score'] - results['mean_test_score'])
    / (-results['mean_train_score'])
) * 100


- The relative gap was used as an additional criterion to evaluate the difference between training and validation performance. This is relevant because the configuration with the lowest validation RMSE is not necessarily the most appropriate if it achieves that performance by fitting the training data excessively well.

- The selected configurations obtain a validation RMSE of approximately 2.99, while the training RMSE is approximately 2.47. This results in a relative gap of 20.75%, meaning that the validation error is about 21% higher than the training error.

- Compared with the configurations with the lowest validation RMSE, this represents a larger validation error, but a much smaller difference between training and validation performance. The smaller gap indicates that the model's performance is more consistent between the data used for training and the validation folds, providing less evidence of strong overfitting.

- The selected configurations also show a clear pattern in their hyperparameters. They use absolute_error as the splitting criterion, sqrt for max_features, and min_samples_leaf=8. These settings restrict the complexity of the individual trees by requiring more observations in each leaf and considering fewer features at each split. This reduces the model's ability to fit very specific patterns in the training data.

- Interestingly, the four configurations shown have exactly the same validation and training scores despite differences in max_depth and min_samples_split. This indicates that, within these configurations, those parameters have little or no measurable effect on the cross-validation performance. In particular, increasing the maximum depth beyond the effective depth reached by the trees does not provide additional predictive benefit.

- The results therefore illustrate a clear trade-off. The lowest-RMSE configurations provide better validation accuracy but show a substantially larger trainvalidation gap, whereas these configurations sacrifice some validation accuracy in exchange for a considerably smaller gap. The 20.75% relative gap suggests a more balanced relationship between training and validation performance.

- However, the relative gap should not be interpreted independently. A smaller gap does not automatically mean better predictive performance; it only indicates that training and validation errors are closer. The final assessment should therefore consider both the validation RMSE and the train validation gap, followed by evaluation on the independent test set that has remained untouched throughout model selection.

In [15]:
results.filter(regex='(param.*|mean_t|std_t|relative_gap_)') \
    .drop(columns='params', errors='ignore') \
    .sort_values('relative_gap_%', ascending=True) \
    .head(4)

,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,mean_test_score,std_test_score,mean_train_score,std_train_score,relative_gap_%
606,absolute_error,30,sqrt,8,4,100,-2.987924,0.130092,-2.474523,0.01193,20.747486
609,absolute_error,30,sqrt,8,8,100,-2.987924,0.130092,-2.474523,0.01193,20.747486
495,absolute_error,20,sqrt,8,2,100,-2.987924,0.130092,-2.474523,0.01193,20.747486
603,absolute_error,30,sqrt,8,2,100,-2.987924,0.130092,-2.474523,0.01193,20.747486


In [16]:
modelo_gab = RandomForestRegressor(
    random_state=random_seed,
    criterion = 'absolute_error',
    max_depth=  30,
    max_features=  'sqrt',
    min_samples_leaf=  8,
    min_samples_split=  8,
    n_estimators= 100
)
modelo_gab.fit(X_train, y_train)

,n_estimators,100
,criterion,'absolute_error'
,max_depth,30
,min_samples_split,8
,min_samples_leaf,8
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


- The two Random Forest configurations were finally evaluated on the same independent test set. This allows their generalization performance to be compared using data that was not involved in the hyperparameter selection process.

- The model selected based on the lowest cross-validation RMSE achieved a test RMSE of 2.3854, while the model selected using the relative train–validation gap achieved a test RMSE of 2.7992.

- The gap-based model showed a much smaller difference between training and validation performance (20.75%), indicating a more balanced fit during cross-validation. However, this greater stability did not translate into better performance on the independent test set. Its test RMSE was approximately 0.414 points higher than that of the model selected by validation RMSE.

- This result highlights an important distinction between model stability and predictive accuracy. A smaller train–validation gap can indicate less overfitting, but it does not guarantee better predictions on unseen data. In this case, the additional constraints applied to the gap-based model reduced the difference between training and validation errors, but also reduced its predictive performance.

- The initial model, despite showing a larger train–validation gap, achieved the lower error on the completely unseen test set. Therefore, the cross-validation results and the final test evaluation provide a more complete picture: the relative gap is useful as a diagnostic for potential overfitting, but it should not be treated as a standalone criterion for model selection.

- The final test evaluation suggests that, for this dataset, the model selected by validation RMSE provides better out-of-sample predictive performance than the more constrained gap-based configuration.

In [17]:
y_predict = modelo_gab.predict(X_test)
root_mean_squared_error(y_test, y_predict)

2.799236870202072

**Apply Oob score**

• When applying oob_score, the parameter oob_score must be set to True.

• The default metric for regression is the coefficient of determination (R²).

The code evaluates each Random Forest configuration using Out-of-Bag (OOB) scoring with R² as the default metric. For each parameter combination, a Random Forest is created with oob_score=True and trained on the full dataset. The resulting OOB R² score is then stored together with its corresponding parameters. Finally, the execution time is recorded to measure the computational cost of evaluating all configurations.

In [18]:
start_time = time.time()
result = {
    'params': [],
    'oob_r2': []
}

for params in dict_params:  
    model_oobscore = RandomForestRegressor(
        oob_score=True,
        n_jobs=-1,
        random_state=random_seed,
        **params
    )

    model_oobscore.fit(X_train, y_train)
    result['params'].append(params)
    result['oob_r2'].append(model_oobscore.oob_score_)

end_time = time.time()

- The OOB R² evaluation took approximately 3.79 minutes (227.26 seconds). OOB scoring is faster than GridSearchCV because it takes advantage of the bootstrap samples already generated for each tree. Each tree is trained on a different sample of the training data, leaving some observations out. These out-of-bag observations can then be used to generate predictions without requiring additional training folds.

- By combining the OOB predictions from the different trees, the model obtains an internal estimate of its performance and calculates the R² score for each hyperparameter configuration. This avoids retraining each configuration across multiple cross-validation folds, substantially reducing the computational cost while still providing a validation signal for comparing the different Random Forest configurations.

In [19]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 244.93153 seconds


- The OOB results show that the best-performing Random Forest configuration achieved an R² of 0.7753, meaning that the model explains approximately 77.5% of the variability in the target variable based on its out-of-bag predictions.

- A clear pattern appears across the top configurations. All of them use squared_error, log2, min_samples_leaf=1, and 200 trees. This suggests that, according to OOB evaluation, the model benefits from allowing relatively flexible tree structures while considering a smaller subset of features at each split.

In [20]:
results_score = pd.DataFrame(result)
results_score = pd.concat(
    [results_score, results_score['params'].apply(pd.Series)], axis=1
)
results_score = results_score.drop(columns = 'params')
results_score = results_score.sort_values('oob_r2', ascending=False)
results_score.head(4)

,oob_r2,criterion,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators
74,0.775295,squared_error,NaN,log2,1,2,200
290,0.775295,squared_error,30.0,log2,1,2,200
182,0.774828,squared_error,20.0,log2,1,2,200
185,0.772709,squared_error,20.0,log2,1,4,200


In [21]:
results_score.head(1)

,oob_r2,criterion,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators
74,0.775295,squared_error,NaN,log2,1,2,200


In [22]:
model_r = RandomForestRegressor(
        oob_score=True,
        n_jobs=-1,
        random_state=random_seed,
        criterion = "squared_error",
        max_depth = None,
        max_features = "log2",
        min_samples_leaf = 1,
        min_samples_split = 2,
        n_estimators = 200
    )

model_r.fit(X_train, y_train)

,n_estimators,200
,criterion,'squared_error'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'log2'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,True


- The OOB approach provides a strong computational trade-off. It required only 3.8 minutes, compared with approximately 22.1 minutes for GridSearchCV around 83% less execution timewhile producing a test RMSE of 2.42, only 0.07 higher than the best GridSearchCV model.

- This suggests that OOB evaluation achieved very competitive predictive performance at a substantially lower computational cost. The gap-based approach, despite explicitly targeting a smaller train–validation gap, required the same expensive GridSearchCV process and ultimately produced a higher test RMSE (2.7992).

In [23]:
y_predict = model_r.predict(X_test)
root_mean_squared_error(y_test, y_predict)

2.4230628500133813

**Apply Oob score other function**


Although the default metric is R², an error function can be used through a callback. For this callback, an error measure such as MAE can be configured to be used as the oob_score.

In [24]:
def metrica_oob_score(y, y_predict, **kwards):
  score = root_mean_squared_error(y, y_predict,**kwards)
  return score

In [25]:
resultados = {
    'params': [],
    'squared_error': []
}

- The OOB score can be configured with a custom evaluation metric instead of relying on the default R². This is useful because the best metric for model selection should reflect the actual objective of the prediction task.

- R² measures how much of the target variance is explained by the model, but it does not directly represent the magnitude of the prediction errors. For a regression problem where minimizing prediction error is the main objective, RMSE can be a more directly interpretable criterion because it measures the typical size of the prediction error and penalizes larger errors more strongly.

- Therefore, using a custom OOB scoring function based on RMSE can make the OOB-based hyperparameter selection more consistent with the metric used in the final model evaluation. R² can still be reported as a complementary performance metric rather than being the sole criterion for model selection.

In [26]:
start_time = time.time()
for params in dict_params:
  model_oobscore = RandomForestRegressor(
      oob_score       = metrica_oob_score,
      n_jobs          =-1,
      random_state    = random_seed,
      **params
  )

  model_oobscore.fit(X_train, y_train)
  resultados['params'].append(params)
  resultados['squared_error'].append(model_oobscore.oob_score_)
end_time = time.time()

- A custom OOB scoring function was implemented using RMSE instead of the default R². This aligns the OOB evaluation with the metric used in the GridSearchCV and final test evaluation, making the model selection process more consistent.

- The evaluation took approximately 4.31 minutes (258.3 seconds). The slightly longer runtime compared with the default OOB R² evaluation (3.79 minutes) is expected because the custom function requires calculating the RMSE from the OOB predictions for each Random Forest configuration.

In [27]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 222.28885 seconds


The best configuration achieves an OOB RMSE of 2.52. The top models show a very similar pattern, using squared_error, log2, min_samples_leaf=1, and 200 trees.

The identical results for max_depth=None and max_depth=30 suggest that increasing the depth beyond 30 does not provide additional benefit. Overall, the OOB evaluation identifies a configuration similar to the one found with GridSearchCV, supporting the

In [28]:
resultados_scores = pd.DataFrame(resultados)
resultados_scores = pd.concat(
    [resultados_scores, resultados_scores['params'].apply(pd.Series)], axis=1)

resultados_scores = resultados_scores.drop(columns = 'params')
resultados_scores = resultados_scores.sort_values('squared_error', ascending=True)
resultados_scores.head(4)

,squared_error,criterion,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators
74,2.521994,squared_error,NaN,log2,1,2,200
290,2.521994,squared_error,30.0,log2,1,2,200
182,2.524613,squared_error,20.0,log2,1,2,200
185,2.536465,squared_error,20.0,log2,1,4,200


In [29]:
model_oob = RandomForestRegressor(
        oob_score=metrica_oob_score,
        n_jobs=-1,
        random_state=random_seed,
        criterion = "squared_error",
        max_depth = None,
        max_features = "log2",
        min_samples_leaf = 1,
        min_samples_split=2,
        n_estimators = 200
    )

model_oob.fit(X_train, y_train)

,n_estimators,200
,criterion,'squared_error'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'log2'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,<function met...x7f9ac0ef4160>


- The custom OOB RMSE metric changes how the model's out-of-bag performance is measured, but it does not change the Random Forest itself. If the same hyperparameters, training data, and random_state are used, the same trees are generated and therefore the predictions on X_test remain identical.

- This explains why the final Test RMSE can be exactly the same when switching from oob_score=True to a custom RMSE function. The difference only affects the evaluation and selection criterion, not the model training process.

- However, different OOB metrics can lead to different model selections when several hyperparameter configurations are compared. R² and RMSE measure different aspects of performance, so they may rank configurations differently. In that case, selecting the configuration using OOB RMSE instead of OOB R² can result in a different final model and, consequently, a different Test RMSE.

- Therefore, identical test results are expected when the selected configuration remains the same. Differences in test performance can occur when the change in OOB metric leads to the selection of a different hyperparameter configuration.

In [30]:
y_predict = model_oob.predict(X_test)
root_mean_squared_error(y_test, y_predict)

2.423062850013381

# **Classification**

## **Data**
---

- A synthetic dataset of 1,000 samples is generated with 10 features, including 7 informative features and 2 redundant features. The problem is formulated as a multiclass classification task with three classes, with class proportions set to 0.50, 0.35, and 0.15, respectively. This distribution introduces a clear class imbalance. Additionally, a class separation parameter (class_sep) of 0.8 is defined to control the degree of separation between the classes.

- The dataset is generated using make_classification, with a fixed random seed to ensure reproducibility. This setup provides a controlled scenario for evaluating model performance in a multiclass classification problem with imbalanced classes. In this context, directly using the default metric associated with oob_score is not appropriate, since a metric such as accuracy may provide a misleading representation of model performance when there is a significant class imbalance. Instead, alternative evaluation metrics can provide a more informative assessment of how the model performs across the different classes.

In [31]:
X, y = make_classification(
    n_samples = 1000,
    n_features = 10,
    n_informative = 7,
    n_redundant = 2,
    n_classes = 3,
    weights = [0.5, 0.35, 0.15],
    class_sep = 0.8,
    random_state=random_seed
)

In [32]:
pd.DataFrame(X).head(3)

,0,1,2,3,4,5,6,7,8,9
0,-1.994293,-0.973313,0.466511,-0.515801,-0.967409,0.580365,0.491026,-1.403556,-1.121424,-1.452780
1,0.696166,0.178325,-0.318898,-3.402707,-1.793873,-2.312178,-0.302448,-0.104724,-0.445917,0.874871
2,0.625275,-0.937379,-0.648134,2.716655,-1.646116,1.649589,-0.225699,-1.275536,2.087411,-3.970914


## **Split**
---

- The dataset is then split into 80% for training and 20% for testing using the train_test_split function. The stratify=y parameter is used to preserve approximately the same proportion of the three classes in both subsets as in the original dataset. This is particularly important in this case due to the class imbalance, as it helps prevent significant changes in the class distribution between the training and test sets.

- Finally, a fixed random seed is specified through the random_state parameter to ensure that the same train-test partition can be reproduced consistently.


In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size = 0.8,
    stratify=y,
    random_state = random_seed
)

## **Model**

**Apply Cross Validation**

- As the first hyperparameter optimization strategy, an exhaustive search is performed using ParameterGrid. This approach generates all possible combinations of the values defined for the main hyperparameters of the classification model. The resulting search space can then be systematically evaluated to identify the configuration that achieves the best performance according to the selected evaluation metric.

- The search considers different values for the number of trees (n_estimators), the criterion used to determine node splits (criterion), the minimum number of samples required to split a node (min_samples_split), and the minimum number of samples required in a leaf node (min_samples_leaf). Different strategies for selecting the features considered at each split are also evaluated through max_features, along with different maximum tree depths specified by max_depth.

- The following values are considered:
  - n_estimators: 100, 150, and 200 trees.
  - criterion: gini and entropy.
  - min_samples_split: 2, 4, and 8 samples.
  - min_samples_leaf: 1, 2, 4, and 8 samples.
  - max_features: 0.75, sqrt, and log2.
  - max_depth: no restriction (None), 20, and 30 levels.


In [34]:
dict_params = ParameterGrid(
    {
        "n_estimators": [100, 150, 200],
        "criterion": ["gini", "entropy"],
        "min_samples_split": [2, 4, 8],
        "min_samples_leaf": [1, 2, 4, 8],
        "max_features": [0.75, "sqrt", "log2"],
        "max_depth": [None, 20, 30],
    }
)

- Once the search space has been defined, GridSearchCV is used to systematically evaluate each hyperparameter combination through cross-validation. A RandomForestClassifier is used as the estimator, configured for parallel processing with n_jobs=-1 and a fixed random seed to ensure reproducibility.

- The evaluation is performed using 5-fold cross-validation (cv=5). For each hyperparameter configuration, the training set is divided into five subsets. Four subsets are used to train the model, while the remaining subset is used for validation. This process is repeated so that each subset is used once for validation, providing a more robust estimate of the performance of each configuration.

- The f1_micro metric is used as the evaluation criterion to assess classifier performance in the multiclass setting. The refit=True parameter specifies that, after identifying the configuration with the best average cross-validation performance, the corresponding model is retrained using the entire training set.

- Additionally, return_train_score=True is enabled to retain the performance results obtained on the training folds. This allows training and validation performance to be compared later and helps identify potential differences associated with model fitting, such as signs of overfitting.

- Finally, the elapsed time for the entire hyperparameter search is recorded by capturing the start and end times using time.time(). This provides a measure of the computational cost associated with the exhaustive search and cross-validation process.

In [35]:
start_time = time.time()
grid = GridSearchCV(
    estimator=RandomForestClassifier(
        n_jobs = -1,
        random_state = random_seed,

    ),
    cv = 5,
    param_grid  = dict_params.param_grid[0],
    scoring     = 'f1_micro',
    refit      = True,
    verbose    = 0,
    return_train_score = True)
grid.fit(X_train, y_train)
end_time = time.time()

- The exhaustive search performed with GridSearchCV required 1,006 seconds to complete, equivalent to approximately 16 minutes. This computational cost is primarily due to the exhaustive nature of the method, as ParameterGrid generates every possible combination of the values defined for the six hyperparameters.

- In this case, the search space contains 432 different hyperparameter combinations. Each configuration is then evaluated using 5-fold cross-validation, resulting in a total of 2,160 model fits during the validation process (432 × 5). Since refit=True is enabled, the best-performing configuration is subsequently retrained using the entire training set.

- Therefore, the approximately 19 minute execution time results from the combination of a relatively large search space and the number of model fits required by cross-validation. This computational cost is inherent to grid search: as more hyperparameters or candidate values are added, the number of possible combinations grows rapidly, which in turn increases the overall computational cost.

In [36]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 1006.09782 seconds


- The model perfectly classifies the data used during training (F1 = 1.00). However, when evaluated using cross-validation, the average F1-score drops to 0.829, representing a gap of approximately 17.1 percentage points compared with the training performance. This difference suggests the presence of overfitting, as the model appears to fit the training data too closely and performs less effectively on data that was not directly used for model fitting. Nevertheless, the average validation F1-score of 0.829, together with its low standard deviation (0.020), indicates relatively stable validation performance across the different folds.

- Overall, the model demonstrates good predictive performance, achieving an F1-score of approximately 83% under cross-validation and maintaining relatively consistent results across folds. However, the substantial gap between training and validation performance indicates that there is still room for improvement in terms of the model's generalization ability.

In [41]:
results = pd.DataFrame(grid.cv_results_)
results.filter(regex = '(param.*|mean_t|std_t)') \
    .drop(columns = 'params') \
    .sort_values('mean_test_score', ascending = False) \
    
results.head(4)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.180681,0.002719,0.027584,0.002635,gini,None,0.75,1,2,100,...,0.82875,0.020387,19,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,0.000000
1,0.261132,0.004339,0.032763,0.005187,gini,None,0.75,1,2,150,...,0.82000,0.015512,205,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,0.000000
2,0.346039,0.002959,0.037125,0.000516,gini,None,0.75,1,2,200,...,0.82500,0.016298,85,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,0.000000
3,0.169206,0.010262,0.025503,0.000404,gini,None,0.75,1,4,100,...,0.82250,0.017941,136,0.998437,0.995313,0.99375,0.99375,0.996875,0.995625,0.001822


In [42]:
best_model_grid = grid.best_estimator_
best_model_grid

,n_estimators,200
,criterion,'entropy'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


- When the selected model was evaluated on the test set, it achieved an F1-score of 0.84, indicating good predictive performance on data that was not used during training. This result is slightly higher than the average F1-score of 0.829 obtained during cross-validation as part of the Grid Search process, with a difference of approximately 1.1 percentage points.

- The similarity between these two results indicates that the performance observed during model selection is maintained when the model is evaluated on independent data. In this regard, the model demonstrates satisfactory generalization ability, as no significant drop in performance is observed on the test set. Although this result is favorable, there is still room for further model optimization and potential improvements in predictive performance.

In [47]:
y_predict = best_model_grid.predict(X_test)
f1_score(y_test, y_predict, average='micro')

0.845

**Apply Oob score**

- To further validate the model's performance and compare the results obtained through Grid Search, a second hyperparameter selection strategy based on the Out-of-Bag (OOB) Score was implemented. This approach estimates model performance using the observations that were not selected for training each tree in the Random Forest, without requiring an additional data partition through cross-validation.

- For this purpose, the previously defined hyperparameter combinations were evaluated by setting oob_score=True for each model. The resulting OOB Score was then recorded for each combination to identify the hyperparameter configuration with the best performance according to this evaluation strategy.

- It is important to note that when oob_score=True is used with RandomForestClassifier, the OOB Score uses accuracy as the default metric. In this case, using accuracy as the selection criterion should be interpreted with caution because the three classes in the dataset are imbalanced. 

In [48]:
start_time = time.time()

results = {
    'params': [],
    'oob_score': []
}

for params in dict_params:
  model_oobscore = RandomForestClassifier(
      oob_score = True,
      n_jobs = -1,
      random_state = random_seed,
      **params
  )
  model_oobscore.fit(X_train, y_train)
  results['params'].append(params)
  results['oob_score'].append(model_oobscore.oob_score_)
end_time = time.time()

- The hyperparameter selection strategy based on the OOB Score had a runtime of 200.02 seconds, equivalent to approximately 3 minutes and 20 seconds, whereas the Grid Search approach required approximately 16 minutes. This represents a substantial reduction in runtime when using the OOB Score, amounting to nearly 79% compared with Grid Search.

- Therefore, in addition to providing an alternative approach for hyperparameter selection, the OOB-based strategy offers a clear advantage in terms of computational efficiency. This can be particularly relevant when working with a large number of hyperparameter combinations, where the computational cost of exhaustive evaluation can become significant.

In [49]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 200.02269 seconds


- The OOB-based strategy identified several hyperparameter configurations with an OOB Score of 0.83625. However, because the OOB Score uses accuracy as its default metric, this result cannot be directly compared with the F1-score obtained through Grid Search. Furthermore, the OOB Score alone does not provide enough information to determine whether overfitting is present, so it must be assessed alongside the model's performance on the training data.

- The final evaluation of the selected configurations will be performed using the F1-score on the test set.

In [50]:
results_score = pd.DataFrame(results)
results_score = pd.concat(
    [results_score, results_score['params'].apply(pd.Series)], axis=1
)

results_score = results_score.drop(columns = 'params')
results_score = results_score.sort_values('oob_score', ascending=False)
results_score.head(4)

,oob_score,criterion,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators
509,0.83625,entropy,20.0,log2,1,4,200
365,0.83625,entropy,NaN,sqrt,1,4,200
473,0.83625,entropy,20.0,sqrt,1,4,200
617,0.83625,entropy,30.0,log2,1,4,200


- The hyperparameter configuration selected using the OOB-based strategy achieved an F1-score of 0.84 when evaluated on the test set. This result matches the performance obtained previously through Grid Search, whose selected model also achieved an F1-score of 0.84 on the same test set.

- This agreement is relevant because the two strategies used different approaches for hyperparameter selection and nevertheless resulted in equivalent predictive performance on independent data. Therefore, in terms of predictive performance, no clear advantage of Grid Search over the OOB-based strategy is observed for this dataset.

- The main difference between the two approaches, however, lies in their computational cost. While Grid Search required approximately 16 minutes, the OOB-based strategy completed the evaluation in approximately 3 minutes and 20 seconds, representing a reduction of nearly 79% in runtime. Consequently, given that both strategies achieved an F1-score of 0.84 on the test set, the OOB-based strategy represents a more computationally efficient alternative for this particular case.

In [52]:
modelo_oob_true = RandomForestClassifier(
      oob_score = False,
      n_jobs = -1,
      random_state = random_seed,
      criterion = "entropy",
      max_depth = 20,
      max_features = "log2",
      min_samples_leaf = 1,
      min_samples_split = 4,
      n_estimators = 200
  )

modelo_oob_true.fit(X_train, y_train)

,n_estimators,200
,criterion,'entropy'
,max_depth,20
,min_samples_split,4
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'log2'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [53]:
y_predict = modelo_oob_true.predict(X_test)
f1_score(y_test, y_predict, average='micro')

0.84

**Apply Oob score other function**

Through a callback, the f1 score  metric is defined.

In [54]:
def metrica_oob_score(y, y_predict, **kwards):
  score = f1_score(y, y_predict, average='micro')
  return score

In [60]:
start_time = time.time()
resultados = {
    'params': [],
    'f1-score': []
}

for params in dict_params:
  model_oobscore = RandomForestClassifier(
      oob_score       = metrica_oob_score,
      n_jobs          =-1,
      random_state    = random_seed,
      **params
  )

  model_oobscore.fit(X_train, y_train)
  resultados['params'].append(params)
  resultados['f1-score'].append(model_oobscore.oob_score_)

end_time = time.time()

- The OOB strategy using the F1-score as a custom evaluation metric had a runtime of 187.40 seconds, equivalent to approximately 3 minutes and 7 seconds. This runtime is slightly lower than that obtained with OOB using accuracy (200.02 seconds), while still maintaining a substantial advantage over the approximately 16 minutes required by Grid Search.

- These results show that using a custom F1-based metric does not introduce a significant increase in computational cost and preserves the efficiency of the OOB-based strategy.

In [61]:
time_exec = end_time - start_time
print(f"Execution time: {time_exec:.5f} seconds")

Execution time: 191.80942 seconds


- This is an interesting result because the four top-performing configurations achieved exactly the same OOB F1-score of 0.83625 (83.63%). This indicates that, under this metric, variations in max_depth and max_features across these configurations do not produce an appreciable difference in the estimated OOB performance.

- The configuration using entropy, min_samples_split=4, min_samples_leaf=1, and n_estimators=200 consistently appears among the top-performing alternatives. However, since all four configurations achieve the same F1-score, it would not be appropriate to claim that one is superior to the others based solely on this result. The final decision can instead be guided by their performance on the test set and, if equivalent results are obtained, by additional criteria such as model complexity or runtime.

In [86]:
results_score = pd.DataFrame(resultados)
results_score = pd.concat(
    [results_score, results_score['params'].apply(pd.Series)], axis=1
)

results_score = results_score.drop(columns = 'params')
results_score = results_score.sort_values('f1-score', ascending=False)
results_score.head(15)

,f1-score,criterion,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators
509,0.83625,entropy,20.0,log2,1,4,200
365,0.83625,entropy,NaN,sqrt,1,4,200
473,0.83625,entropy,20.0,sqrt,1,4,200
617,0.83625,entropy,30.0,log2,1,4,200
401,0.83625,entropy,NaN,log2,1,4,200
581,0.83625,entropy,30.0,sqrt,1,4,200
362,0.83500,entropy,NaN,sqrt,1,2,200
506,0.83500,entropy,20.0,log2,1,2,200
470,0.83500,entropy,20.0,sqrt,1,2,200
578,0.83500,entropy,30.0,sqrt,1,2,200


In [87]:
modelo_oob_call = RandomForestClassifier(
      oob_score = False,
      n_jobs = -1,
      random_state = random_seed,
      criterion = "entropy",
      max_depth = 20,
      max_features = "log2",
      min_samples_leaf = 1,
      min_samples_split = 4,
      n_estimators = 200
  )

modelo_oob_call.fit(X_train, y_train)

,n_estimators,200
,criterion,'entropy'
,max_depth,20
,min_samples_split,4
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'log2'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


- The OOB strategy using the F1-score as a custom metric once again achieved a performance of approximately 0.84, similar to the results obtained through both Grid Search and OOB using accuracy. In addition, the main configurations evaluated produced nearly identical F1-scores, indicating that model performance remains stable across the hyperparameter variations considered.

- This behavior may indicate that, within the explored hyperparameter space, the changes made are not sufficient to produce a meaningful improvement in model performance. Therefore, the results do not necessarily suggest that there is a clearly superior configuration; rather, performance appears to stabilize around an F1-score of 0.84 across the evaluated alternatives.

- Consequently, achieving a higher level of performance may require expanding the hyperparameter search space or exploring alternative modeling strategies. If performance continues to remain around this level regardless of the configuration used, it would also be worth examining the available features and considering feature engineering techniques or alternative algorithms that may capture relationships that Random Forest is not adequately leveraging.

In [88]:
y_predict = modelo_oob_call.predict(X_test)
f1_score(y_test, y_predict, average='micro')

0.84

# **Info**
---
**@By:** **Kaiziferr**

**@Git:** https://github.com/Kaiziferr